githubteacher/dev-mar-6

edlutes-Raleigh-NC.md

This pull requests adds Raleigh NC to the list of hometowns.
Looks like it could be the 3rd-4th instance of Raleigh
This PR closes #18.

edlutes adds Raleigh NC to the list of home towns

---

turnev-slc.md

This pull request is to add SLC, UT to the list of hometowns.
This PR closes #6

turnev adds SLC,UT

---

vishaka-bangalore.md

Vishaka adds Bangalore, IN

---

prohit99-bangalore.md

Added places to see and restaurants

Prohit99 bangalore

---

juan-tex-edinburgh.md

This pull request is to add Edinburgh, UK, to the list of hometowns. 
@mpvelarde @davidtextensor Check it out :D

juan-tex adds Edinburgh, UK

---

lamarr246-RaleighNC.md

This pull request is to add the Raleigh, NC attractions to the list of hometowns.
@jdmize what kinds of things do you like to do in Raleigh, NC?
This PR closes #32

Add lamarr246 raleigh nc pull request

---

davegthemighty-nyc.md

Description
This pull request closes #25

Davegthemighty adds nyc

---

toddsloan63-wakeforest.md

This pull request is to add WakeForest

Toddsloan63 wakeforest

---

mikeSie-Boston.md

This Pull Request is to add Boston, MA to the list of hometowns.
This PR closes #44.

mikeSie adds Boston, MA

---

ATP93-Košice.md

This Pull Request is to add Košice, Slovakia to the list of hometowns
This PR closes #42 .

ATP93 adds Košice, Slovakia

---

mbackspacep-OverlandPark.md

This PR is to add Overland Park to the list of hometowns. 
Made some changes to mbackspacep-OverlandPark.md 
This PR Closes #37

Add Overland Park,KS 

---

Vijaybabu27-Manchester.md

This Pull request is to add Manchester, CT to the list of Hometowns
@githubteacher what kind of things would you like to do with your son in Manchester, CT
This PR closed #45

GithubTeacher adds Manchester, CT

---

venugopalrohit-boston.md

This is a pull request for adding boston, ma file
This PR closes #35

Rohit adds boston, ma

---

alfie698-glasgow.md

This request is to add Glasgow to the list of hometowns.
This Pull Request closes #26

Alfie698 adds Glasgow Scotland

---

FisherChen3-Waltham.md

This pull request is to add waltham to the list of hometowns
cross reference to the issues
#21

FisherChen3 add waltham

---

ShaunHaageCLAB-DURBAN.md

This pull request is to add Durban , South Africa to the list of hometowns.
@MarkyStuart , what kind bru?
This PR closes #71.

ShaunHaageCLAB adds Durban, South Africa

---

chris-jones23-Fort-Collins.md

This Pull Request it to add Fort Collins, CO to the list of hometowns.
This PR closes #24.

chris-jones23 adds Fort Collins, CO

---

sighte-dublin.md

This pull request is to add Dublin, Ireland to the list of hometowns.
This PR closes #29.

Sighte adds Dublin

---

githubteacher-orlando.md

This Pull Request is to add Orlando, FL to the list of hometowns. 
@crichID what kinds of things would you like to do with your son when you visit Orlando?
This PR closes #20.

GitHubTeacher adds Orlando, FL 

---

davidtextensor-edinburgh.md

This Pull Request is to add Edinburgh,UK to the list of hometowns.

davidtextensor adds Edinburgh,UK 

---

mpvelarde-edinburgh.md

This pull request is to add Edinburgh,UK to the list of hometowns.
This PR closes #51

Mpvelarde adds Edinburgh

---

alessandro-bugatti-brescia.md

This Pull Request is to add Brescia, Italy to the list of hometowns.
This PR closes #38

alessandro-bugatti adds Brescia, Italy

---

manners15-salemAL.md

This pull request is to add Salem, AL to the list of hometowns.
This PR closes #49 .

manners15 adding Salem, AL to the list of Hometowns

---

rahulnaik4-mumbai-india.md
rahulnaik4-mumbai-india/rahulnaik4-mumbai-india.md

This pull request is to add mumbai, India to the list of hometowns.
@crichID what kind of things would you like to do with your son when you visit mumbai.
This PR closes #40

rahulnaik4 adds mumbai, India

---

jdmize-knightdale.md

This pull request is to add Knightdale, NC to the list of hometowns.
This PR closes #39.

jdmize adds Knightdale, NC

---

MarkyStuart-Durban-SA.md

This pull request is to add Durban,SA to the list of hometowns
Anything you like @ShaunHaageCLAB ?
This PR closes #12

MarkyStuart adds Durban, SA 

---

SeePrashant-RockyHill.txt
SeePrashant-RockyHill.txt.txt

This Pull request is to add Rocky Hill, CT to list of hometown.
@vijayshivhare89 what would you like to do when in Rocky Hill, CT ? 
@N081613 How its Going?
@N774092 how are you ?
This PR closes #50 Issue.

seePrashant Adds Rocky hill, CT

---

hi2satish-cary.md

This pull request is to add Cary, NC to list of hometowns.
approve this if you want to know some cool stuff about cary!
@githubteacher, @crichID let me know when you are in town of cary.
This PR closes #16

Hi2satish adds cary, NC

---

Damaris-Landers-ManchesterUK.md

This Pull Request is to add Manchester, UK to the list of hometowns.
@daveearley @pH-7 users chosen to mention at random 😄 
This Pull Request closes #36.

Damaris Landers adds Manchester, UK

---

ro-orlando

Visit Orlando to enjoy Disney parks
HI @githubteacher , I am orlando too.

Oralndo - a dream place to visit

---

shij10-chengdu.md

This pull request is to add Chengdu, China to the list of hometowns
@crichID welcome to my city.
The PR closes #56

Shij10 adds Chengdu, China

---

subhashbabum-bangalore.md

This is a git training first pull 
This PR closes #30

Subhash adds Bangalore, IN

---

PhaniPenumaka-Hartford.md

This pull request is to add Hartford,CT to the list of hometown
@vijayshivhare89 - At what time shall i book uber for office 
This PR closes #20

PhaniPenumaka adds Hartford,CT

---

vijayshivhare89-RockyHill.md

This pull request is to add Rocky Hill, CT to the list of hometowns.
@PhaniPenumaka When are you planning to go office?
This PR closes #50.

vijayshivhare89 adds RockyHill, CT

---

MichaelKennedy39-Castleton.md

Add MichaelKennedy39 hometown Castleton Vt

Michael kennedy39 castleton

---

sua3-shanghai.md

Sua3 shanghai

---

lamarr246_2-file2

This pull request is reviewing day 1 steps for the GitHub training. Commiting a new file.

lamarr246_2 - commit new file lamarr246_2-file2
